// Mocks generated by Mockito 5.4.2 from annotations
// in asklora_mobile_app/test/learning/demonstration_question_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:asklora_mobile_app/feature/learning/demonstration_question/repository/demonstration_question_repository.dart'
    as _i2;
import 'package:asklora_mobile_app/feature/onboarding/ppi/domain/question.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DemonstrationQuestionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDemonstrationQuestionRepository extends _i1.Mock
    implements _i2.DemonstrationQuestionRepository {
  MockDemonstrationQuestionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Question>> fetchQuestions() => (super.noSuchMethod(
        Invocation.method(
          #fetchQuestions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
      ) as _i3.Future<List<_i4.Question>>);
}
