name: asklora_mobile_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.10.0'

dependencies:
  built_value: ^8.6.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.1
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.1
  logger: any
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  dart_ipify: ^1.1.1
  intl: ^0.18.1
  device_info_plus: ^9.0.3
  file_picker: ^5.3.3
  collection: ^1.17.1
  package_info_plus: ^4.1.0
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  photo_view: ^0.14.0
  google_fonts: ^5.1.0
  back_button_interceptor: ^7.0.0
  onfido_sdk: ^4.0.0
  just_the_tooltip: ^0.0.12
  sentry_flutter: ^7.9.0
  showcaseview:
    # path: ../flutter_showcaseview

  country_picker:
    # path: ../flutter_country_picker/

  fl_chart:
    # path: ../asklora-flutter-chart/fl_chart
  uni_links: ^0.5.1
  path_provider: ^2.1.0
  auto_size_text_field: ^2.2.1
  auto_size_text: ^3.0.0
  flutter_keyboard_visibility: ^5.4.1
  video_player: ^2.7.0
  firebase_messaging: ^14.6.6

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.6
  built_value_generator: ^8.6.1
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  http_mock_adapter: ^0.4.4
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  intl_translation: ^0.18.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/apng/
    - assets/videos/
    - assets/json/
    - assets/
    - .env
    - google_fonts/
  fonts:
    - family: Manrope
      fonts:
        - asset: google_fonts/Manrope-Bold.ttf
          weight: 700
        - asset: google_fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Manrope-Light.ttf
          weight: 300
        - asset: google_fonts/Manrope-Medium.ttf
          weight: 500
        - asset: google_fonts/Manrope-Regular.ttf
          weight: 400
        - asset: google_fonts/Manrope-SemiBold.ttf
          weight: 600
    - family: NotoSansTC
      fonts:
        - asset: google_fonts/NotoSansTC-Black.otf
          weight: 900
        - asset: google_fonts/NotoSansTC-Bold.otf
          weight: 700
        - asset: google_fonts/NotoSansTC-Light.otf
          weight: 300
        - asset: google_fonts/NotoSansTC-Medium.otf
          weight: 500
        - asset: google_fonts/NotoSansTC-Regular.otf
          weight: 400
        - asset: google_fonts/NotoSansTC-Thin.otf
          weight: 100
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
