name: Building Dev and Staging APK and IPA

on:
  workflow_call:
  push:
    branches:
      - master
      - development
      - 'release/**'
      - 'chore/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Get flutter dependencies.
      - run: make get

      # Check for any formatting issues in the code.
      - run: make format

      # Statically analyze the Dart code for any errors.
      - run: make lint

      # Run widget tests for our flutter project.
      - run: make run_test